"""
PDF Report Generator using ReportLab
"""

from datetime import datetime
from typing import Dict, Any
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, Image
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT


class PDFGenerator:
    """Generate PDF reports with ReportLab"""

    def __init__(self):
        self.styles = getSampleStyleSheet()
        self._add_custom_styles()

    def _add_custom_styles(self):
        """Add custom styles"""
        self.styles.add(ParagraphStyle(
            name='CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#2c3e50'),
            spaceAfter=30,
            alignment=TA_CENTER,
        ))

        self.styles.add(ParagraphStyle(
            name='SectionHeading',
            parent=self.styles['Heading2'],
            fontSize=16,
            textColor=colors.HexColor('#2c3e50'),
            spaceAfter=12,
            spaceBefore=12,
        ))

    def generate_executive_pdf(
        self,
        findings: Dict[str, Any],
        target: str,
        output_file: str,
    ):
        """Generate executive PDF report"""
        print(f"[*] Creating executive PDF: {output_file}")

        doc = SimpleDocTemplate(output_file, pagesize=letter)
        story = []

        # Title
        title = Paragraph(
            f"🛡️ Security Assessment<br/>{target}",
            self.styles['CustomTitle'],
        )
        story.append(title)
        story.append(Spacer(1, 0.3 * inch))

        # Date
        date_para = Paragraph(
            f"<b>Report Date:</b> {datetime.now().strftime('%B %d, %Y')}",
            self.styles['Normal'],
        )
        story.append(date_para)
        story.append(Spacer(1, 0.5 * inch))

        # Executive Summary
        story.append(Paragraph("Executive Summary", self.styles['SectionHeading']))

        summary_text = "This report presents the findings of a comprehensive security assessment."
        story.append(Paragraph(summary_text, self.styles['Normal']))
        story.append(Spacer(1, 0.3 * inch))

        # Risk Summary Table
        if findings:
            story.append(Paragraph("Risk Summary", self.styles['SectionHeading']))

            risk_data = [
                ['Severity', 'Count', 'Risk Level'],
                ['Critical', '0', 'CRITICAL'],
                ['High', '0', 'HIGH'],
                ['Medium', '0', 'MEDIUM'],
                ['Low', '0', 'LOW'],
            ]

            risk_table = Table(risk_data, colWidths=[2 * inch, 1.5 * inch, 2 * inch])
            risk_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#2c3e50')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 12),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
                ('GRID', (0, 0), (-1, -1), 1, colors.black),
            ]))

            story.append(risk_table)
            story.append(Spacer(1, 0.5 * inch))

        # Recommendations
        story.append(Paragraph("Key Recommendations", self.styles['SectionHeading']))

        recommendations = [
            "1. Address critical vulnerabilities immediately",
            "2. Implement security hardening measures",
            "3. Conduct regular security assessments",
            "4. Provide security awareness training",
        ]

        for rec in recommendations:
            story.append(Paragraph(rec, self.styles['Normal']))
            story.append(Spacer(1, 0.1 * inch))

        # Footer
        story.append(Spacer(1, 1 * inch))
        footer = Paragraph(
            "<i>Generated by Sec-Llama Suite - CONFIDENTIAL</i>",
            self.styles['Normal'],
        )
        story.append(footer)

        # Build PDF
        doc.build(story)
        print(f"[+] PDF generated successfully")

    def generate_technical_pdf(
        self,
        findings: Dict[str, Any],
        target: str,
        output_file: str,
    ):
        """Generate technical PDF report"""
        print(f"[*] Creating technical PDF: {output_file}")

        doc = SimpleDocTemplate(output_file, pagesize=A4)
        story = []

        # Title
        title = Paragraph(
            f"Technical Security Assessment<br/>{target}",
            self.styles['CustomTitle'],
        )
        story.append(title)
        story.append(Spacer(1, 0.5 * inch))

        # Methodology
        story.append(Paragraph("Methodology", self.styles['SectionHeading']))
        methodology_text = """This assessment was conducted using the Sec-Llama Suite,
        an AI-powered security testing framework. The testing included network discovery,
        port scanning, vulnerability assessment, and exploit analysis."""
        story.append(Paragraph(methodology_text, self.styles['Normal']))
        story.append(Spacer(1, 0.3 * inch))

        # Findings
        story.append(Paragraph("Detailed Findings", self.styles['SectionHeading']))

        if findings:
            import json
            findings_text = f"<pre>{json.dumps(findings, indent=2)[:500]}...</pre>"
            story.append(Paragraph(findings_text, self.styles['Code']))

        # Build PDF
        doc.build(story)
        print(f"[+] Technical PDF generated successfully")
