"""
Advanced Report Generator
Generate professional security reports in multiple formats
"""

import json
from datetime import datetime
from typing import Dict, Any, List
from pathlib import Path

from core.config import get_config
from core.llm_interface import get_llm


class ReportGenerator:
    """Generate professional security reports"""

    def __init__(self):
        self.config = get_config()
        self.llm = get_llm()
        self.report_dir = Path(self.config.reporting.output_dir)
        self.report_dir.mkdir(parents=True, exist_ok=True)

    def generate_executive_report(
        self,
        findings: Dict[str, Any],
        target: str,
    ) -> str:
        """
        Generate executive summary report

        Args:
            findings: Security findings
            target: Target assessed

        Returns:
            Path to generated report
        """
        print("[*] Generating executive report...")

        from core.prompt_templates import PromptTemplates

        # Create summary with AI
        findings_str = json.dumps(findings, indent=2)[:2000]  # Truncate for prompt

        prompt = PromptTemplates.get_executive_summary_prompt(findings_str)

        try:
            summary = self.llm.generate(prompt)

            report_data = {
                "title": f"Security Assessment - {target}",
                "date": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                "target": target,
                "executive_summary": summary,
                "findings": findings,
            }

            # Save as HTML
            output_file = self.report_dir / f"executive_report_{target.replace('/', '_')}_{datetime.now().strftime('%Y%m%d')}.html"

            html = self._generate_executive_html(report_data)

            with open(output_file, "w") as f:
                f.write(html)

            print(f"[+] Executive report saved: {output_file}")
            return str(output_file)

        except Exception as e:
            print(f"[!] Report generation failed: {e}")
            return ""

    def generate_technical_report(
        self,
        findings: Dict[str, Any],
        target: str,
    ) -> str:
        """Generate detailed technical report"""
        print("[*] Generating technical report...")

        from core.prompt_templates import PromptTemplates

        findings_str = json.dumps(findings, indent=2)[:3000]

        prompt = PromptTemplates.get_technical_report_prompt(findings_str)

        try:
            technical_details = self.llm.generate(prompt)

            report_data = {
                "title": f"Technical Security Assessment - {target}",
                "date": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                "target": target,
                "technical_details": technical_details,
                "findings": findings,
            }

            output_file = self.report_dir / f"technical_report_{target.replace('/', '_')}_{datetime.now().strftime('%Y%m%d')}.html"

            html = self._generate_technical_html(report_data)

            with open(output_file, "w") as f:
                f.write(html)

            print(f"[+] Technical report saved: {output_file}")
            return str(output_file)

        except Exception as e:
            print(f"[!] Report generation failed: {e}")
            return ""

    def _generate_executive_html(self, data: Dict[str, Any]) -> str:
        """Generate executive HTML report"""
        return f"""<!DOCTYPE html>
<html>
<head>
    <title>{data['title']}</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 40px; line-height: 1.6; }}
        .header {{ background: #2c3e50; color: white; padding: 30px; margin: -40px -40px 40px -40px; }}
        .header h1 {{ margin: 0; }}
        .section {{ margin: 30px 0; }}
        .critical {{ color: #e74c3c; font-weight: bold; }}
        .high {{ color: #e67e22; font-weight: bold; }}
        .medium {{ color: #f39c12; }}
        .low {{ color: #27ae60; }}
        pre {{ background: #ecf0f1; padding: 15px; border-radius: 5px; overflow-x: auto; }}
        .footer {{ margin-top: 50px; padding-top: 20px; border-top: 2px solid #ecf0f1; font-size: 0.9em; color: #7f8c8d; }}
    </style>
</head>
<body>
    <div class="header">
        <h1>🛡️ {data['title']}</h1>
        <p>Generated: {data['date']}</p>
    </div>

    <div class="section">
        <h2>Executive Summary</h2>
        <div>{data['executive_summary'].replace(chr(10), '<br>')}</div>
    </div>

    <div class="section">
        <h2>Target Information</h2>
        <p><strong>Target:</strong> {data['target']}</p>
    </div>

    <div class="footer">
        <p>Generated by Sec-Llama Suite - Local LLM-Powered Cybersecurity Testing</p>
        <p><strong>CONFIDENTIAL</strong> - This report contains sensitive security information</p>
    </div>
</body>
</html>"""

    def _generate_technical_html(self, data: Dict[str, Any]) -> str:
        """Generate technical HTML report"""
        return f"""<!DOCTYPE html>
<html>
<head>
    <title>{data['title']}</title>
    <style>
        body {{ font-family: 'Courier New', monospace; margin: 40px; line-height: 1.6; background: #1e1e1e; color: #d4d4d4; }}
        .header {{ background: #2d2d2d; color: #4ec9b0; padding: 30px; margin: -40px -40px 40px -40px; border-bottom: 3px solid #4ec9b0; }}
        .section {{ margin: 30px 0; background: #252526; padding: 20px; border-radius: 5px; }}
        .critical {{ color: #f48771; font-weight: bold; }}
        .high {{ color: #ce9178; font-weight: bold; }}
        .medium {{ color: #dcdcaa; }}
        .low {{ color: #4ec9b0; }}
        pre {{ background: #1e1e1e; padding: 15px; border: 1px solid #3c3c3c; border-radius: 5px; overflow-x: auto; }}
        h2 {{ color: #4ec9b0; border-bottom: 2px solid #3c3c3c; padding-bottom: 10px; }}
    </style>
</head>
<body>
    <div class="header">
        <h1>🔧 {data['title']}</h1>
        <p>Generated: {data['date']}</p>
    </div>

    <div class="section">
        <h2>Technical Analysis</h2>
        <pre>{data['technical_details']}</pre>
    </div>

    <div class="section">
        <h2>Detailed Findings</h2>
        <pre>{json.dumps(data['findings'], indent=2)}</pre>
    </div>
</body>
</html>"""

    def generate_pdf_report(
        self,
        findings: Dict[str, Any],
        target: str,
        report_type: str = "executive",
    ) -> str:
        """
        Generate PDF report

        Args:
            findings: Security findings
            target: Target assessed
            report_type: Report type (executive or technical)

        Returns:
            Path to PDF file
        """
        print(f"[*] Generating {report_type} PDF report...")

        from .pdf_generator import PDFGenerator

        pdf_gen = PDFGenerator()

        output_file = self.report_dir / f"{report_type}_report_{target.replace('/', '_')}_{datetime.now().strftime('%Y%m%d')}.pdf"

        if report_type == "executive":
            pdf_gen.generate_executive_pdf(findings, target, str(output_file))
        else:
            pdf_gen.generate_technical_pdf(findings, target, str(output_file))

        if Path(output_file).exists():
            print(f"[+] PDF report saved: {output_file}")
            return str(output_file)

        return ""

    def generate_compliance_report(
        self,
        findings: Dict[str, Any],
        framework: str = "OWASP",
    ) -> str:
        """
        Generate compliance report

        Args:
            findings: Security findings
            framework: Compliance framework (OWASP, PCI-DSS, etc.)

        Returns:
            Path to report
        """
        print(f"[*] Generating {framework} compliance report...")

        prompt = f"""Analyze the following security findings against {framework} framework:

Findings:
{json.dumps(findings, indent=2)[:2000]}

Provide:
1. **Compliance Status**: Overall compliance rating
2. **Violations**: Specific {framework} requirements violated
3. **Remediation**: Steps to achieve compliance
4. **Priority**: Which violations to fix first

Format as a compliance report."""

        try:
            compliance_analysis = self.llm.generate(prompt)

            output_file = self.report_dir / f"compliance_{framework}_{datetime.now().strftime('%Y%m%d')}.txt"

            with open(output_file, "w") as f:
                f.write(f"{framework} Compliance Report\n")
                f.write("=" * 80 + "\n\n")
                f.write(compliance_analysis)

            print(f"[+] Compliance report saved: {output_file}")
            return str(output_file)

        except Exception as e:
            print(f"[!] Compliance report generation failed: {e}")
            return ""
